# -*- coding: utf-8 -*-
"""Simple name and age question bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O62_WzsCGruorjOYupE-CphtO8ImwC3T
"""

name = input("type your name here: ")
age = input("type your age here: ")

print("Hi ", name, " you are ", age, " years old.")